image:
  file: .gitpod.Dockerfile


tasks:
  - before: sdk use java 16.0.1.hs-adpt
  - name: Dev server
    init: |
      cd mavenprojectest/backend
      mvn clean install
    command: mvn spring-boot:run
  - name: Start frontend
    command: |
      gp ports await 8080
      echo port open
    openMode: split-right

