image:
  file: .gitpod.Dockerfile


tasks:
  - name: Start backend server
  - init: sdk use java 16.0.1.hs-adpt &&
          cd mavenprojectest/backend &&
          mvn clean install &&
          mvn spring-boot:start
    command: cd ..
  - name: start frontend ui
  command: echo "test"


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: notify
