image:
  file: .gitpod.Dockerfile


tasks:
  - before: sdk use java 16.0.1.hs-adpt
  - name: Dev server
    init: |
      cd mavenprojectest/backend
      mvn clean install
    command: mvn spring-boot:run
  - name: Start frontend
    init: |
      cd mavenprojectest/frontend/src/main/reactui
      npm install
    command: |
      gp ports await 8080
      npm start
    openMode: split-right

ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-browser