image:
  file: .gitpod.Dockerfile


tasks:
  - name: Start backend server
  - init: sdk use java 16.0.1.hs-adpt &&
          cd mavenprojectest/backend &&
          mvn clean install &&
          mvn spring-boot:start
    command: cd ..
  - name: Start frontend
    command: echo hello
    openMode: split-right


